/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VWD7EbDbr9s
 */
import Link from "next/link"
import { CardContent, CardFooter, Card } from "@/components/ui/card"
import Image from "next/image"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"


export function Component() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 py-4 lg:py-6 flex items-center">
        <div className="flex items-center space-x-2">
          <Link className="flex items-center space-x-2" href="#">
            <SunsetIcon className="h-6 w-6" />
            <span className="font-bold text-2xl">HAI</span>
          </Link>
        </div>
        
      </header>
      <main className="grid gap-6 lg:gap-12 px-4 lg:px-6">
        <div className="space-y-4 lg:space-y-0 lg:grid lg:grid-cols-[1fr_2fr] lg:items-center lg:gap-12 xl:grid-cols-[1fr_3fr]">
          <div className="flex flex-col justify-center space-y-2">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl md:text-6xl/none">Hi, I'm Hai Trinh</h1>
            <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              I build web experiences.
            </p>
          </div>
          <div className="mx-auto max-w-3xl space-y-6 lg:space-y-10">
            <Image
              alt="Hero"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center"
              height="320"
              src="/placeholder.svg"
              width="600"
            />
          </div>
        </div>
        <div className="space-y-4">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">My Projects</h2>
          <p className="max-w-[800px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            Here are some of the projects I have been working on.
          </p>
        </div>
        <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">
          {/**CMS Vue */}
          <Card>
            <CardContent className="p-4">
              <div className="flex justify-between items-start">
                <h3 className="text-base font-bold">Vuetify UI Library</h3>
                <div className="flex items-center space-x-2">
                  <CodeIcon className="h-4 w-4" />
                </div>
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Collaborated with a software engineer to create a UI library using VueJS as the core
              </p>
            </CardContent>
            <CardFooter className="flex p-4 items-center">
              <Button className="ml-auto h-8" variant="outline">
                <Link href={'https://github.com/quachthientai/cms-vue-template'} >View Details</Link>
                
              </Button>
            </CardFooter>
          </Card>

          {/**Burger Project */}
          <Card>
            <CardContent className="p-4">
              <div className="flex justify-between items-start">
                <h3 className="text-base font-bold">Burger Restaurant</h3>
                <div className="flex items-center space-x-2">
                  <CodeIcon className="h-4 w-4" />
                </div>
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                A fictional burger restaurant website that offer features such as order online and table reservation
              </p>
            </CardContent>
            <CardFooter className="flex p-4 items-center">
              <Button className="ml-auto h-8" variant="outline">
                <Link href={'https://github.com/n2ai/burger-web'} >View Details</Link>
              </Button>
            </CardFooter>
          </Card>
          {/**Messenger Clone */}
          <Card>
            <CardContent className="p-4">
              <div className="flex justify-between items-start">
                <h3 className="text-base font-bold">Messenger Clone</h3>
                <div className="flex items-center space-x-2">
                  <CodeIcon className="h-4 w-4" />
                </div>
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                A clone website of Messenger in which real-time chat is enable
              </p>
            </CardContent>
            <CardFooter className="flex p-4 items-center">
              <Button className="ml-auto h-8" variant="outline">
                <Link href={'https://messenger-clone-ksfp-lyrl64t84-doan-long-hai-trinhs-projects.vercel.app/'} >View Details</Link>
              </Button>
            </CardFooter>
          </Card>
          {/**Cheap flight chromium extension */}
          <Card>
            <CardContent className="p-4">
              <div className="flex justify-between items-start">
                <h3 className="text-base font-bold">Cheap Flight Chromium Extension</h3>
                <div className="flex items-center space-x-2">
                  <CodeIcon className="h-4 w-4" />
                </div>
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                A Google Chrome extension AI chat box that allow users to use natural language to search for flight tickets
              </p>
            </CardContent>
            <CardFooter className="flex p-4 items-center">
              <Button className="ml-auto h-8" variant="outline">
                <Link href={'https://github.com/tng296/cheap-flight-chromium-extension'} >View Details</Link>
              </Button>
            </CardFooter>
          </Card>
          {/**University Courses Management */}
          <Card>
            <CardContent className="p-4">
              <div className="flex justify-between items-start">
                <h3 className="text-base font-bold">University Course Management</h3>
                <div className="flex items-center space-x-2">
                  <CodeIcon className="h-4 w-4" />
                </div>
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                A web application that help university student in planning their degree, pick class and check class availability. This
                project limit to Computer Science major
              </p>
            </CardContent>
            <CardFooter className="flex p-4 items-center">
              <Button className="ml-auto h-8" variant="outline">
                <Link href={'https://github.com/n2ai/coursesManagement'} >View Details</Link>
              </Button>
            </CardFooter>
          </Card>
        </div>
      </main>
    </div>
  )
}


function SunsetIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 10V2" />
      <path d="m4.93 10.93 1.41 1.41" />
      <path d="M2 18h2" />
      <path d="M20 18h2" />
      <path d="m19.07 10.93-1.41 1.41" />
      <path d="M22 22H2" />
      <path d="m16 6-4 4-4-4" />
      <path d="M16 18a4 4 0 0 0-8 0" />
    </svg>
  )
}


function CodeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  )
}
